version : "3"
services :
  nginx:
    image: ghcr.io/vitalii-dubovoi/nginx-proxy:1.0.0 
    container_name: nginx_container
    ports:
      - 80:8080
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf